### PR TITLE
Remove unused models

### PR DESCRIPTION
**Pull request by feng-tao**
### Summary of Changes

With https://github.com/lyft/amundsenmetadatalibrary/pull/64/files, we have checked in some models that currently are not used. Going to remove those unless we plan to use those in the near future.

### Tests

_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes. 
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes `make test`
- [ ] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by feng-tao** [comment]
cc @jinhyukchang

**Comment by feng-tao** [comment]
cc @friendtocephalopods as well

**Comment by friendtocephalopods** [comment]
Oops, sorry about that! I removed those from the Table before creating the PR but I missed removing the classes.

`ForeignKey` might be generally useful to others as a column attribute, but `PiiDetail` and `DataDetail` are probably a bit notional to upstream just yet.

**Comment by feng-tao** [comment]
@friendtocephalopods thanks for the confirmation and contribution. No worry :) Let's remove the classes for now and we could add it back once we introduce the related use case. Sounds good?

**Comment by friendtocephalopods** [comment]
Sounds good to me!

**Pull request merged**
