### PR TITLE
Updates atlas proxy implementation to match terminology

### PR DESCRIPTION
**Pull request by verdan**
In order to make it consistent with the existing terms of Amundsen, this PR updates the way it was using db and schema name to generate the table URI. 
We'll make a more concrete discussion about the terms in an issue opened in frontend library https://github.com/lyft/amundsenfrontendlibrary/issues/61

### CODE REVIEW

**Comment by verdan** [comment]
@feng-tao @jinhyukchang ready for review.

**Comment by jinhyukchang** [comment]
@verdan I believe this PR is contingent to this [issue](https://github.com/lyft/amundsenfrontendlibrary/issues/61). I just replied to the issue, and let me know what you think.

Thanks for the suggestion!
Jin

**Comment by verdan** [comment]
@jinhyukchang this PR is still valid, as previously I was assuming `database` as the database name, `schema` as the database schema like public etc., and was sending the data from atlas proxy based on that. This PR would fix that issue for atlas proxy.

**Comment by verdan** [comment]
@feng-tao nope. I already have the next PR ready, was waiting for this one. And i will bump the version in that one.

**Comment by feng-tao** [comment]
sounds good.

**Pull request merged**
