### PR TITLE
Change neo4j relationships to single-directional

### PR DESCRIPTION
**Pull request by friendtocephalopods**
### Summary of Changes

Remove `_OF`-type secondary relationships as they seem to have little benefit. See https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1563487877254000 and https://gist.github.com/friendtocephalopods/14c5b59f3ace8772ca2d502c928bb641 for a more detailed analysis of why this is okay.

### Tests

No tests modified, since it's a refactor that shouldn't change test behavior.

### Documentation

No documentation added or modified.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x ] PR includes a summary of changes. 
- [x ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [x ] PR passes `make test`
- [x ] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by friendtocephalopods** [comment]
@feng-tao per the slack, recommended review request procedure is tag someone manually?

**Comment by feng-tao** [comment]
@friendtocephalopods , sorry for delay in review. thanks for tagging . Currently I am busy with oncall , will take a look once oncall is done.

also cc @jinhyukchang in case Jin has cycle.

**Comment by feng-tao** [comment]
@friendtocephalopods , haven't dived into the detail, but I thought the conclusion for your previous perf test is that no perf difference between bi-direction and single direction?

**Comment by friendtocephalopods** [comment]
@feng-tao yep! if there's no appreciable performance benefit in querying from having multiple connections, might as well save the space and only make one connection for all these things?

**Comment by feng-tao** [comment]
I bump the version actually. Should be good.

**Comment by friendtocephalopods** [comment]
Great, looks like it just needs a re-stamp then!

**Comment by feng-tao** [comment]
thanks @friendtocephalopods , and sorry for the delay :)

**Pull request merged**
