### PR TITLE
Clean up user endpoints and add BaseAPI

### PR DESCRIPTION
**Pull request by alran**
### Summary of Changes

This PR adds tests for user endpoints that were previously untested. It also adds a BaseAPI and uses this BaseAPI in the UserDetailAPI. 

### Tests

I added tests for the user endpoints.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes `make test`

### CODE REVIEW

**Comment by alran** [comment]
@feng-tao

**Comment by feng-tao** [comment]
will take a look

**Comment by feng-tao** [comment]
@alran just merge an openapi pr which seems to break yours sorry :(. Could you rebase your pr and update it? Thanks.

**Comment by alran** [comment]
yep! let me do that now...

**Comment by alran** [comment]
looks like there was an awk rebase, but I just cleaned it up and force pushed. Tests should pass now...

**Pull request merged**
